apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: default
data:
  index.html: |
    <html>
    <body>
    <h1>typing cat on </h1>
    <?php echo gethostname(); ?>
    </body>
    </html>
