apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: default
data:
  index.html: |
    <html>
    <h1>typing cat on </h1>
    <?php
    echo "typing cat on ";
    echo gethostname();
    ?>
    </html
